### ISSUE TITLE
Whitespace trimming support

### ISSUE THREAD

**Issue by webrgp** [kaermorchen/twig-parser#13]
Hi @kaermorchen!

I am working on a prettier plugin for Twig and I came across your parser, which looks great from my initial testing. But I am a bit bummed out that the Whitespace trimming isn't supported. Can you care to explain what the issue is? I am incline to take a stab at it, but I just wanted to check with you before diving into a rabbit whole.

Looking at `lexer.ts`, it seems that you do support it on VariableTokens and BlockTokens. So what's the issue?

Thanks!

**Comment by kaermorchen** [comment]
Hi @webrgp.

> Can you care to explain what the issue is?

Final AST doesn't have whitespace trimming structures. For example `{{ 42 }}` and `{{~ 42 ~}}` will have the same AST.

Check out [tree-sitter-twig](https://github.com/kaermorchen/tree-sitter-twig), it have CST output but supports more features.

**Comment by webrgp** [comment]
I guess it's fine for my purposes since all I need is to be able to identify the nodes in the AST so I can apply formatting rules. But I will check out tree-sitter, thanks!

**Comment by webrgp** [comment]
I've checked your `tree-sitter-twig`. How's it different from [gbprod/tree-sitter-twig](https://github.com/gbprod/tree-sitter-twig)?

**Comment by kaermorchen** [comment]
gbprod/tree-sitter-twig don't support some twig features

**Comment by webrgp** [comment]
I think for my purposes this twig parser will do. Why did you write it to begin with?

**Comment by webrgp** [comment]
I do most on my work these days on Craft CMS, which uses Twig. Unfortunately there isn't a good prettier plugin for it.
